export const TAGS = [
  "Automation",
  "Browser Tools",
  "Calculators & Converters",
  "Date & Time",
  "Development Tools",
  "Documentation",
  "File Management",
  "Gaming",
  "Multimedia",
  "Networking",
  "Productivity",
  "Programming",
  "Search",
  "System",
  "Text Tools",
  "Translation",
  "Social Media",
  "Utilities",
] as const;
